import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "@/utils/fonts";
import { ClerkProvider } from "@clerk/nextjs";

import { SanityLive } from "@/sanity/lib/live";
import { DisableDraftMode } from "@/sanity/components/DisableDraftMode";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
          <SanityLive />
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}
        </body>
      </html>
    </ClerkProvider>
  );
}
