import type { Metadata } from "next";
import "../globals.css";

import { geistMono, geistSans } from "@/utils/fonts";

import { draftMode } from "next/headers";
import { ClerkProvider } from "@clerk/nextjs";
import { SanityLive } from "@/sanity/lib/live";
import DraftModeToast from "@/sanity/components/DraftModeToast";
import { VisualEditing } from "next-sanity";
import { LiveErrorBoundary } from "@/sanity/components/LiveErrorBoundary";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled: isDraftMode } = await draftMode();
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
          <SanityLive />
          {isDraftMode && (
            <>
              <DraftModeToast />
              <VisualEditing />
            </>
          )}
          <LiveErrorBoundary>
            <SanityLive />
          </LiveErrorBoundary>
        </body>
      </html>
    </ClerkProvider>
  );
}
